---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-1730196649987
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-1730196649987 
  name: chatbot-1730196649987
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi